### PR TITLE
[BEAM-3388] Use typeswitch instead of reflect.Convert

### PR DESCRIPTION
**Pull request by lostluck**
In coder.go when encoding []bytes or strings for transit

### CODE REVIEW

**Comment by herohde** [comment]
LGTM

**Comment by herohde** [comment]
Btw, please use BEAM-3388 or a new JIRA in the description

**Comment by lostluck** [comment]
R: @aaltay (please merge)

**Comment by aaltay** [comment]
I do not have write access, it seems like this PR is for your personal fork, not for the apache/beam repo.

**Comment by lostluck** [comment]
@aaltay You appear to be correct. I don't have a good github process at the moment. 
Closing this and starting a new one. Thanks!

**Pull request merged**
